### ISSUE TITLE
Add missing badges like jCasbin

### ISSUE THREAD

**Issue by hsluoyz** [jcasbin/redis-watcher#13]
See: https://github.com/casbin/jcasbin

![image](https://user-images.githubusercontent.com/3787410/137930579-561a8aa9-3bbd-4ca7-987c-9ac4e802abd8.png)

**Comment by seriouszyx** [comment]
> @seriouszyx

I will add it right now.

**Comment by seriouszyx** [comment]
I have added some badges in https://github.com/jcasbin/redis-watcher/pull/14.
But for [codebeat](https://codebeat.co/) and [codecov](https://codecov.io/gh),  repo admin access is required.

**Comment by hsluoyz** [comment]
@seriouszyx permission granted, plz setup codebeat and codecov

**Comment by hsluoyz** [comment]
Fixed by: https://github.com/jcasbin/redis-watcher/pull/14
