### ISSUE TITLE
Redis sub exception occurs and sync becomes invalid

### ISSUE THREAD

**Issue by yu-hailong** [jcasbin/redis-watcher#29]
I used redis-watcher for distribute sync. 
If I did not push message on provider about five minutes, and the following error happened, 
![image](https://user-images.githubusercontent.com/17443614/179178014-7bb23af9-040e-474e-8aa1-3e09152d9c5f.png)

and , after the exception happened, even I did push message on provider, the following is not executed
![image](https://user-images.githubusercontent.com/17443614/179178781-3a37a9f5-e64c-495a-b7d0-a90c2f26423e.png)

maybe it is relation with the redis-server settings 
![image](https://user-images.githubusercontent.com/17443614/179178911-6fb98877-f877-4b8c-b202-7481be96e021.png)

**Comment by yu-hailong** [comment]
Would you please help and give me some suggestion to avoid the problem, 
we find the problem on product - env. thanks a lot

**Comment by yu-hailong** [comment]
if exception happened ,should we  "do  while " and try to get a new jedis and subscibe again ??

![image](https://user-images.githubusercontent.com/17443614/179183088-bb8baa4a-6ef0-4788-87da-e7db071eeeb5.png)

**Comment by imp2002** [comment]
It may be that server setting up the timeout not zero, it means after one period connection is disposed or closed. I'm not sure if a connect which is in subscribe will be closed by server, it's a guess.

Solution is set timeout on server to 0.

And Resubscribe when an exception is thrown is necessary. Thank you for Issue and PR.
